language: python

matrix:
  allow_failures:
    - python: "2.7"

python:
    - "2.7"
    - "3.6"
    - "3.7"

branches:
  only:
  - master

sudo: false

install:
    - pip install Inspektor==0.5.3

script:
    - inspekt checkall --disable-style E501,E265,W601,W605,E402,E722,E741 --no-license-check
